#!/bin/bash
usage="\
Installs dotfiles in home directory

Options:
    -u --uninstall  Remove symlinked dotfiles
    -p --plugins    Install vim plugins also
    -h --help       Print this help message

"
dot_base=`basename ${BASH_SOURCE[0]%\/*}`
cd  # $dot_base must be in home directory

case "$1" in
  '-u'|'--uninstall')
    uninstall='true';;
  '-p'|'--plugins')
    plugins='true';;
  '-h'|'--help')
    echo "$usage"
    return 2>/dev/null || exit 0;;
esac

for f in ${dot_base}/*; do
  fbase=${f//*\/}
  case $fbase in
    'install')
      continue;;
    'mac')
      test `uname -s` != 'Darwin' && continue;;
    *);;
  esac
  if test "$uninstall" = 'true'; then
    rm -v .$fbase
  else
    ln -ivs $f .$fbase
  fi
done

if test "$plugins" = 'true'; then
  if ! test -d ~/.vim/bundle/Vundle.vim; then
    git clone https://github.com/VundleVim/Vundle.vim ~/.vim/bundle/Vundle.vim
  fi
  vim +PluginInstall +qall
fi

