#!/bin/bash

function clr () { # (number, text)
  printf "\033[38;5;${1}m${2}\033[0m"
}

SPHardwareDataType="$(system_profiler SPHardwareDataType)"
SPDisplaysDataType="$(system_profiler SPDisplaysDataType)"

user=$USER
sw=$(sw_vers | perl -lane 'print "@F[1..$#F]"' | tr '\n' ' ')
k_arch=$(uname -m)
k_os="$(sysctl -n kern.ostype) $(sysctl -n kern.osrelease)"
hw=$(echo "$SPHardwareDataType" \
       | perl -ne 'print $1 if /(MacBookPro[0-9]+,[0-9]+)/')
shell=${SHELL//*\/}
sh_v=${BASH_VERSION%\(*}
font="$(jq -r '."Normal Font"' ~/.dotfiles/config/iterm/maneyko.json)"

npack=$(
  d=(/usr/local/opt/* /usr/local/Caskroom/*)
  echo ${#d[@]}
)
nbin=$(
    for d in ${PATH//:/ }; do
      s+=($d/*)
    done
    echo ${#s[@]}
)

vim_v=$($EDITOR --version \
          | perl -ne 'print $& if /[0-9]+\.[0-9]+(\.[0-9]+)?/ && $.==1')

res=$(echo "$SPDisplaysDataType" \
        | perl -ne 'print "$1" if /Resolution: (.*)/')

cpu=$(sysctl -n machdep.cpu.brand_string \
        | perl -pe 's/[(R)(TM)]//g')

gpu=$(echo "$SPDisplaysDataType" \
        | awk -F ': ' '/Chipset/ {print $2; exit}')

ram=$(echo "$SPHardwareDataType" \
        | awk -F ': ' '/Memory/ {print $2; exit}')

cat << EOT

$(clr 2 "                  -/+:.           ")
$(clr 2 "                 :++++.           ")
$(clr 2 "                /+++/.            "; clr 6 'Username:'  ) $user
$(clr 2 "        .:-::- .+/:-''.::-        "; clr 6 'OS:'        ) $sw
$(clr 2 "     .:/++++++/::::/++++++/:'     "; clr 6 'Kernel:'    ) $k_arch $k_os
$(clr 3 "   .:///////////////////////:'    "; clr 6 'Hardware:'  ) $hw
$(clr 3 "   ////////////////////////'      "; clr 6 'Shell:'     ) $shell $sh_v
$(clr 1 "  -+++++++++++++++++++++++'       "; clr 6 'Packages:'  ) $npack
$(clr 1 "  /++++++++++++++++++++++/        "; clr 6 'Binaries:'  ) $nbin
$(clr 1 "  /sssssssssssssssssssssss.       "; clr 6 '$EDITOR:'   ) $EDITOR $vim_v
$(clr 1 "  :ssssssssssssssssssssssss-      "; clr 6 'Resolution:') $res
$(clr 5 "   osssssssssssssssssssssssso/'   "; clr 6 'Font:'      ) $font
$(clr 5 "   'syyyyyyyyyyyyyyyyyyyyyyyy+'   "; clr 6 'CPU:'       ) $cpu
$(clr 4 "    'ossssssssssssssssssssss/     "; clr 6 'GPU:'       ) $gpu
$(clr 4 "      :ooooooooooooooooooo+.      "; clr 6 'RAM:'       ) $ram
$(clr 4 "       ':+oo+/:-..-:/+o+/-")

EOT
