#!/bin/bash

function clr () { # (number, text)
  printf "\033[38;5;${1}m${2}\033[0m"
}

sp_hardware_file=$HOME/.dotfiles/mac/SPHardwareDataType.txt
sp_displays_file=$HOME/.dotfiles/mac/SPDisplaysDataType.txt

if test -f $sp_hardware_file; then
  SPHardwareDataType="$(cat $sp_hardware_file)"
else
  SPHardwareDataType="$(system_profiler SPHardwareDataType | tee $sp_hardware_file)"
fi

if test -f $sp_displays_file; then
  SPDisplaysDataType="$(cat $sp_displays_file)"
else
  SPDisplaysDataType="$(system_profiler SPDisplaysDataType | tee $sp_displays_file)"
fi

user=$USER
sw=$(sw_vers | perl -lane 'print "@F[1..$#F]"' | tr '\n' ' ')
k_arch=$(uname -m)
k_os="$(sysctl -n kern.ostype) $(sysctl -n kern.osrelease)"
hw=$(perl -ne 'print $1 if /(Mac[bB]ookPro[0-9]+,[0-9]+)/' \
       <<< "$SPHardwareDataType")
shell=${SHELL//*\/}
sh_v=${BASH_VERSION%\(*}
font="$(defaults read com.googlecode.iTerm2 "New Bookmarks" | awk -F'"' '/Normal Font/ {print $4; exit}')"

npack=$(
  d=(/usr/local/opt/* /usr/local/Caskroom/*)
  echo ${#d[@]}
)
nbin=$(
    for d in ${PATH//:/ }; do
      s+=($d/*)
    done
    echo ${#s[@]}
)

vim_v=$($EDITOR --version \
          | perl -ne 'print $& if /[0-9]+\.[0-9]+(\.[0-9]+)?/ && $.==1')

res=$(perl -ne 'print "$1" if /Resolution: (.*)/' \
        <<< "$SPDisplaysDataType")

cpu=$(sysctl -n machdep.cpu.brand_string \
        | perl -pe 's/[(R)(TM)]//g')

gpu=$(awk -F ': ' '/Chipset/ {print $2; exit}' \
        <<< "$SPDisplaysDataType")

ram=$(awk -F ': ' '/Memory/ {print $2; exit}' <<< "$SPHardwareDataType")

cat << EOT

$(clr 2 "                  -/+:.           ")
$(clr 2 "                 :++++.           ")
$(clr 2 "                /+++/.            "; clr 6 'Username:'  ) $user
$(clr 2 "        .:-::- .+/:-''.::-        "; clr 6 'OS:'        ) $sw
$(clr 2 "     .:/++++++/::::/++++++/:'     "; clr 6 'Kernel:'    ) $k_arch $k_os
$(clr 3 "   .:///////////////////////:'    "; clr 6 'Hardware:'  ) $hw
$(clr 3 "   ////////////////////////'      "; clr 6 'Shell:'     ) $shell $sh_v
$(clr 1 "  -+++++++++++++++++++++++'       "; clr 6 'Packages:'  ) $npack
$(clr 1 "  /++++++++++++++++++++++/        "; clr 6 'Binaries:'  ) $nbin
$(clr 1 "  /sssssssssssssssssssssss.       "; clr 6 '$EDITOR:'   ) $(basename $EDITOR) $vim_v
$(clr 1 "  :ssssssssssssssssssssssss-      "; clr 6 'Resolution:') $res
$(clr 5 "   osssssssssssssssssssssssso/'   "; clr 6 'Font:'      ) $font
$(clr 5 "   'syyyyyyyyyyyyyyyyyyyyyyyy+'   "; clr 6 'CPU:'       ) $cpu
$(clr 4 "    'ossssssssssssssssssssss/     "; clr 6 'GPU:'       ) $gpu
$(clr 4 "      :ooooooooooooooooooo+.      "; clr 6 'RAM:'       ) $ram
$(clr 4 "       ':+oo+/:-..-:/+o+/-")

EOT

# clean up
vars=$(perl -ne 'print "$1\n" if /([0-9A-Za-z]+)=/' "$BASH_SOURCE")
for v in $vars; do
  unset $v
done
