return function(colors)
  return {
    cssBraces               = { link = "colorsboxBlue" },
    cssFunctionName         = { link = "colorsboxYellow" },
    cssIdentifier           = { link = "colorsboxOrange" },
    cssClassName            = { link = "colorsboxGreen" },
    cssColor                = { link = "colorsboxBlue" },
    cssSelectorOp           = { link = "colorsboxBlue" },
    cssSelectorOp2          = { link = "colorsboxBlue" },
    cssImportant            = { link = "colorsboxGreen" },
    cssVendor               = { link = "colorsboxFg1" },
    cssTextProp             = { link = "colorsboxAqua" },
    cssAnimationProp        = { link = "colorsboxAqua" },
    cssUIProp               = { link = "colorsboxYellow" },
    cssTransformProp        = { link = "colorsboxAqua" },
    cssTransitionProp       = { link = "colorsboxAqua" },
    cssPrintProp            = { link = "colorsboxAqua" },
    cssPositioningProp      = { link = "colorsboxYellow" },
    cssBoxProp              = { link = "colorsboxAqua" },
    cssFontDescriptorProp   = { link = "colorsboxAqua" },
    cssFlexibleBoxProp      = { link = "colorsboxAqua" },
    cssBorderOutlineProp    = { link = "colorsboxAqua" },
    cssBackgroundProp       = { link = "colorsboxAqua" },
    cssMarginProp           = { link = "colorsboxAqua" },
    cssListProp             = { link = "colorsboxAqua" },
    cssTableProp            = { link = "colorsboxAqua" },
    cssFontProp             = { link = "colorsboxAqua" },
    cssPaddingProp          = { link = "colorsboxAqua" },
    cssDimensionProp        = { link = "colorsboxAqua" },
    cssRenderProp           = { link = "colorsboxAqua" },
    cssColorProp            = { link = "colorsboxAqua" },
    cssGeneratedContentProp = { link = "colorsboxAqua" },
  }
end
