return function(colors)
  return {
    javaScriptBraces               = { link = "colorsboxFg1" },
    javaScriptFunction             = { link = "colorsboxAqua" },
    javaScriptIdentifier           = { link = "colorsboxRed" },
    javaScriptMember               = { link = "colorsboxBlue" },
    javaScriptNumber               = { link = "colorsboxPurple" },
    javaScriptNull                 = { link = "colorsboxPurple" },
    javaScriptParens               = { link = "colorsboxFg3" },
    javascriptImport               = { link = "colorsboxAqua" },
    javascriptExport               = { link = "colorsboxAqua" },
    javascriptClassKeyword         = { link = "colorsboxAqua" },
    javascriptClassExtends         = { link = "colorsboxAqua" },
    javascriptDefault              = { link = "colorsboxAqua" },
    javascriptClassName            = { link = "colorsboxYellow" },
    javascriptClassSuperName       = { link = "colorsboxYellow" },
    javascriptGlobal               = { link = "colorsboxYellow" },
    javascriptEndColons            = { link = "colorsboxFg1" },
    javascriptFuncArg              = { link = "colorsboxFg1" },
    javascriptGlobalMethod         = { link = "colorsboxFg1" },
    javascriptNodeGlobal           = { link = "colorsboxFg1" },
    javascriptVariable             = { link = "colorsboxRed" },
    javascriptIdentifier           = { link = "colorsboxOrange" },
    javascriptClassSuper           = { link = "colorsboxOrange" },
    javascriptFuncKeyword          = { link = "colorsboxAqua" },
    javascriptAsyncFunc            = { link = "colorsboxAqua" },
    javascriptClassStatic          = { link = "colorsboxOrange" },
    javascriptOperator             = { link = "colorsboxRed" },
    javascriptForOperator          = { link = "colorsboxRed" },
    javascriptYield                = { link = "colorsboxRed" },
    javascriptExceptions           = { link = "colorsboxRed" },
    javascriptMessage              = { link = "colorsboxRed" },
    javascriptTemplateSB           = { link = "colorsboxAqua" },
    javascriptTemplateSubstitution = { link = "colorsboxFg1" },
    javascriptLabel                = { link = "colorsboxFg1" },
    javascriptObjectLabel          = { link = "colorsboxFg1" },
    javascriptPropertyName         = { link = "colorsboxFg1" },
    javascriptLogicSymbols         = { link = "colorsboxFg1" },
    javascriptArrowFunc            = { link = "colorsboxFg1" },
    javascriptDocParamName         = { link = "colorsboxFg4" },
    javascriptDocTags              = { link = "colorsboxFg4" },
    javascriptDocNotation          = { link = "colorsboxFg4" },
    javascriptDocParamType         = { link = "colorsboxFg4" },
    javascriptDocNamedParamType    = { link = "colorsboxFg4" },
  }
end
