return function(colors)
  return {
    colorsboxFg0  = { fg = colors.fg0 },
    colorsboxFg1  = { fg = colors.fg1 },
    colorsboxFg2  = { fg = colors.fg2 },
    colorsboxFg3  = { fg = colors.fg3 },
    colorsboxFg4  = { fg = colors.fg4 },
    colorsboxGray = { fg = colors.gray },
    colorsboxBg0  = { fg = colors.bg0 },
    colorsboxBg1  = { fg = colors.bg1 },
    colorsboxBg2  = { fg = colors.bg2 },
    colorsboxBg3  = { fg = colors.bg3 },
    colorsboxRed  = { fg = colors.red },
    colorsboxRedBold    = { fg = colors.red, bg = colors.none, style = { "bold" } },
    colorsboxGreen      = { fg = colors.green },
    colorsboxGreenBold  = { fg = colors.green, bg = colors.none, style = { "bold" } },
    colorsboxYellow     = { fg = colors.yellow },
    colorsboxYellowBold = { fg = colors.yellow, bg = colors.none, style = { "bold" } },
    colorsboxBlue       = { fg = colors.blue },
    colorsboxBlueBold   = { fg = colors.blue, bg = colors.none, style = { "bold" } },
    colorsboxPurple     = { fg = colors.purple },
    colorsboxPurpleBold = { fg = colors.purple, bg = colors.none, style = { "bold" } },
    colorsboxAqua       = { fg = colors.aqua },
    colorsboxAquaBold   = { fg = colors.aqua, bg = colors.none, style = { "bold" } },
    colorsboxOrange     = { fg = colors.orange },
    colorsboxOrangeBold = { fg = colors.orange, bg = colors.none, style = { "bold" } },
    colorsboxRedSign    = { fg = colors.red,    bg = colors.bg1 },
    colorsboxGreenSign  = { fg = colors.green,  bg = colors.bg1 },
    colorsboxYellowSign = { fg = colors.yellow, bg = colors.bg1 },
    colorsboxBlueSign   = { fg = colors.blue,   bg = colors.bg1 },
    colorsboxPurpleSign = { fg = colors.purple, bg = colors.bg1 },
    colorsboxAquaSign   = { fg = colors.aqua,   bg = colors.bg1 },
  }
end
