#!/bin/bash

cd ~/

mv ~/dotfiles/ ~/.dotfiles/ || (echo Move ~/.dotfiles/ && exit 1)

bases="\
.dotfiles/bash/
.dotfiles/bin/
.dotfiles/config/
.dotfiles/tmux/
.dotfiles/utils/
.dotfiles/vim/
.bash/bashrc
.bash/bash_profile
.bash/inputrc
.tmux/tmux.conf
.vim/vimrc
"

mkdir ~/.dotfiles/backup/
for base in $bases; do

  link=`basename $base`

  if test -f ~/.$link; then
    cat ~/.$link >> ~/.$link.bak
    mv ~/.$link ~/.dotfiles/backup/$link
  fi

  ln -s $base .$link

done

. ~/.bashrc

if test "$1" == "--plugins" -o "$1" == "-p" ; then
  git clone https://github.com/VundleVim/Vundle.vim ~/.vim/bundle/Vundle.vim
  vim +PluginInstall +qall
fi

