#!/bin/sh

cd ~/dotfiles/

for file in $(ls | grep -v setup); do
    
    if [ -f ~/.$file ]; then
        if [ ! -d ~/dotfiles/setup/dotfiles_old ]; then
            mkdir ~/dotfiles/setup/dotfiles_old
        fi
        echo "moving ~/.$file to ~/dotfiles/setup/dotfiles_old/$file"
        mv ~/.$file ~/dotfiles/setup/dotfiles_old/$file
    fi
done

setup/install
