#!/bin/bash

cd ~/

mv ~/dotfiles/ ~/.dotfiles/ || (echo Move ~/.dotfiles/ && exit 1)

bases="\
.dotfiles/bash/
.dotfiles/bin/
.dotfiles/config/
.dotfiles/tmux/
.dotfiles/utils/
.dotfiles/vim/
.bash/bashrc
.bash/bash_profile
.bash/inputrc
.tmux/tmux.conf
.vim/vimrc
"

mkdir ~/.dotfiles/backup/
for base in $bases; do
  name="`basename "$base"`"
  if test -f .$name; then
    cat .$name >> ~/.$name.local
    mv .$name ~/.dotfiles/backup/$name
  fi
  ln -s $base .$name
done

. ~/.bashrc

if test "$1" == "--plugins" -o "$1" == "-p" ; then
  git clone https://github.com/VundleVim/Vundle.vim ~/.vim/bundle/Vundle.vim
  vim +PluginInstall +qall
fi

